default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: movies-collection
  pool: 5
  username:
  password:
  socket: /var/run/mysqld/mysqld.sock


development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
